### ISSUE TITLE
stuck already

### ISSUE THREAD

**Issue by rogierslag** [inventid/mannie#1]
@joostverdoorn I could help myself to start with this.

However I cannot seem to output text.

```jsx
<MjText align={alignment}
                  font-size={GlobalLayout.fonts.sizes.medium}
                  color={GlobalLayout.colors.white}
                  font-family={GlobalLayout.fonts.families.montserrat}
                  font-weight="200" content="EXAMPLE CONTENT 2" />
``` 
does not work.

```jsx
<MjText align={alignment}
                  font-size={GlobalLayout.fonts.sizes.medium}
                  color={GlobalLayout.colors.white}
                  font-family={GlobalLayout.fonts.families.montserrat}
                  font-weight="200">EXAMPLE CONTENT 2</MjText>
```
even throws an error

Any ideas?

**Comment by rogierslag** [comment]
Made a propsed fix for the project, but I really dislike the way their react stuff is setup. Its not intuitive at all. I think we might be faster to create our own mjml components instead of building react stuff

**Comment by joostverdoorn** [comment]
You have probably figured this out already, but both your provided examples will never work with react for one simple reason: you cannot have dashes in property names!

```<MjText font-size={GlobalLayout.fonts.sizes.medium} />``` 
should be 
```<MjText fontSize={GlobalLayout.fonts.sizes.medium} />``` 
if anything. Although I suspect you should set things like `fontSize` in a `style` property.

Also, let's stop calling the layout module `GlobalLayout` already. That name has been bothering me for a while in morpheus, but seeing it repeated elsewhere really grinds my gears ;). I propose to call it simply Layout or Theme.

**Comment by rogierslag** [comment]
The dashes actually work. Just use the array notation ;)

**Comment by joostverdoorn** [comment]
I learned something today

**Comment by rogierslag** [comment]
Turns out it was a bug in MJML, fixed in https://github.com/mjmlio/mjml/pull/98
